spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/book
        username: bapun
        password: malik@123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    mvc:
        view:
            prefix: /templates/
            suffix: .html